---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: production
type: Opaque
data:
  username: YWRtaW4=  # admin en base64
  password: cGFzc3dvcmQxMjM=  # password123 en base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: production
  labels:
    app: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
      - name: api
        image: node:16-alpine
        command: ["sleep", "3600"]
        ports:
        - containerPort: 3000
        env:
        - name: DB_PASSWORD
          value: "hardcoded-password"  # Problème: mot de passe en dur
        - name: API_KEY
          value: "sk-1234567890abcdef"  # Problème: clé API en dur
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        # Problème: pas de limites de ressources
        securityContext:
          allowPrivilegeEscalation: true  # Problème de sécurité
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: production
spec:
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP

