---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: production
data:
  database_url: "postgresql://admin:secretpassword@db:5432/myapp"  # Problème: credentials en clair
  api_key: "sk-1234567890abcdef"  # Problème: clé API en clair
  debug_mode: "true"
  log_level: "debug"

