---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-panel
  namespace: staging
  labels:
    app: admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-panel
  template:
    metadata:
      labels:
        app: admin-panel
    spec:
      containers:
      - name: admin
        image: httpd:2.4
        ports:
        - containerPort: 80
        # Problème: pas de configuration de sécurité
---
apiVersion: v1
kind: Service
metadata:
  name: admin-panel-service
  namespace: staging
spec:
  selector:
    app: admin-panel
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort  # Problème: exposition directe

