---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: production
  labels:
    app: database
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
        tier: data
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "weak-password"  # Problème: mot de passe faible
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "myapp"
        # Problème: pas de volume persistant
        # Problème: pas de limites de ressources
        securityContext:
          runAsUser: 0  # Problème: root user
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: production
spec:
  selector:
    app: database
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

