---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-configmap-secrets
  annotations:
    policies.kyverno.io/title: Check ConfigMap for Secrets
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: ConfigMap
    policies.kyverno.io/description: >-
      ConfigMaps should not contain sensitive information like passwords, tokens, or API keys.
      Use Secrets instead for sensitive data.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: check-sensitive-data
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
    validate:
      message: "ConfigMaps should not contain sensitive data like passwords or API keys."
      deny:
        conditions:
          any:
          - key: "{{ request.object.data | to_entries(@) | [?contains(value, 'password') || contains(value, 'secret') || contains(value, 'token') || contains(key, 'password') || contains(key, 'secret') || contains(key, 'token')] | length(@) }}"
            operator: GreaterThan
            value: 0

