---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-env-secrets
  annotations:
    policies.kyverno.io/title: Check Environment Variables for Secrets
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      Environment variables should not contain hardcoded secrets like passwords,
      API keys, or tokens. Use Secrets or ConfigMaps instead.
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: check-env-vars
    match:
      any:
      - resources:
          kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
    validate:
      message: "Environment variables should not contain hardcoded secrets. Found suspicious patterns in environment variables."
      deny:
        conditions:
          any:
          - key: "{{ request.object.spec.containers[?contains(env[?contains(name, 'PASSWORD') || contains(name, 'SECRET') || contains(name, 'TOKEN') || contains(name, 'KEY')].value, 'password') || contains(env[?contains(name, 'PASSWORD') || contains(name, 'SECRET') || contains(name, 'TOKEN') || contains(name, 'KEY')].value, 'secret') || contains(env[?contains(name, 'PASSWORD') || contains(name, 'SECRET') || contains(name, 'TOKEN') || contains(name, 'KEY')].value, 'key')] | length(@) }}"
            operator: GreaterThan
            value: 0

