---
apiVersion: v1
kind: Pod
metadata:
  name: appli-latest
  namespace: default
spec:
  containers:
  - name: appli-container
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: appli-version
  namespace: default
spec:
  containers:
  - name: appli-container
    image: nginx:1.27.5
---
apiVersion: v1
kind: Pod
metadata:
  name: appli-prometheus
  namespace: default
spec:
  containers:
  - name: appli-prometheus
    image: prom/node-exporter:v1.9.1
